import "./globals.css";
import AuthProvider from "@/components/admin/AuthProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* set auth  */}
        <AuthProvider>{children}</AuthProvider>
        {/* ser auth  */}
      </body>
    </html>
  );
}
